name: CICD

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t paulhana6006/studyolle .
      - name: Published image to docker hub
        run: docker push paulhana6006/studyolle:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: KKTRKKT/studyolle-prod-env
          token: ${{secrets.PAT}}
      - name: Pull docker image
        run: sudo docker pull paulhana6006/studyolle
      - name: Remove docker container
        run: sudo docker compose down
      - name: Run docker container
        run: sudo docker compose up -d


